train:
  _target_: src.datasets.LibrispeechDataset
  part: "train_all"
  max_audio_length: 18
  max_text_length: 240
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.LibrispeechDataset
  part: "dev-clean"
  instance_transforms: ${transforms.instance_transforms.inference}
test:
  _target_: src.datasets.LibrispeechDataset
  part: "test-clean"
  instance_transforms: ${transforms.instance_transforms.inference}