train: # metrics that are calculated during training
  - _target_: src.metrics.ArgmaxCERMetric
    name: "CER_(Argmax)" # it is better to avoid spaces in names
  - _target_: src.metrics.ArgmaxWERMetric
    name: "WER_(Argmax)"
  # - _target_: src.metrics.BeamSearchCERMetric
  #   name: "CER_(BeamSearch)" # it is better to avoid spaces in names
  #   lm_use: ${text_encoder.lm_use}
  # - _target_: src.metrics.BeamSearchWERMetric
  #   name: "WER_(BeamSearch)"
  #   lm_use: ${text_encoder.lm_use}
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.ArgmaxCERMetric
    name: "CER_(Argmax)" # it is better to avoid spaces in names
  - _target_: src.metrics.ArgmaxWERMetric
    name: "WER_(Argmax)"
  - _target_: src.metrics.BeamSearchCERMetric
    name: "CER_(BeamSearch)" # it is better to avoid spaces in names
    lm_use: ${text_encoder.lm_use}
  - _target_: src.metrics.BeamSearchWERMetric
    name: "WER_(BeamSearch)"
    lm_use: ${text_encoder.lm_use}