train:
  data_object: spectrogram
  _target_: torch.nn.Sequential # to apply several transforms sequentially
  _args_:
    - _target_: src.transforms.spec_augs.Normalize1D
      mean: 0.5
      std: 0.5
    - _target_: src.transforms.spec_augs.FrequencyMasking
      freq_mask_param: 10
    - _target_: src.transforms.spec_augs.TimeMasking
      time_mask_param: 10
inference:
  data_object: spectrogram
  _target_: torch.nn.Sequential # to apply several transforms sequentially
  _args_:
    - _target_: src.transforms.spec_augs.Normalize1D
      mean: 0.5
      std: 0.5
