defaults:
  - model: conformer
  - writer: cometml
  - metrics: example
  - datasets: default
  - dataloader: 32_size
  - transforms: first_run_only_inst
  - _self_
optimizer:
  _target_: torch.optim.AdamW
  lr: 1
lr_scheduler:
  _target_: src.model.NoamScheduler
  d_model: 176
  warmup_steps: 360
loss_function:
  _target_: src.loss.CTCLossWrapper
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
  beam_use: True
  lm_use: False
  bpe_use: False
  vocab_size: 128
  beam_size: 3
trainer:
  log_step: 20
  n_epochs: 20
  epoch_len: null
  device_tensors: ["spectrogram", "text_encoded"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: True # if True, will override the previous run with the same name
  monitor: "min val_WER_(Argmax)" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 5 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 1
  use_accelerate: True
  fp16: True
  max_grad_norm: 5
  grad_acum_steps: 4