defaults:
  - model: deepspeech
  - metrics: example
  - datasets: final_dataset
  - dataloader: 64_size
  - transforms: example
  - _self_
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
  beam_use: True
  lm_use: False
  bpe_use: False
  vocab_size: 128
  beam_size: 3
inferencer:
  device_tensors: ["spectrogram", "text_encoded"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "first_inf" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "saved/testing/model_best.pth" # path to the pretrained model
